name: "Release"

on:
  push:
    tags: []

jobs:
  build:
    name: Build 🛠️
    uses: ./.github/workflows/run_build.yml

  release:
    needs:
      - build
    name: Create Release 📢
    runs-on: ubuntu-latest
    steps:
      - name: Download Tarball 📥
        uses: actions/download-artifact@v4
        with:
          name: tarball

      - name: Generate Checksums 🔑
        run: |
          sha256sum nixos.wsl > nixos.wsl.sha256

      - name: Attach to Release 📎
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nixos.wsl
            nixos.wsl.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
