name: "Everyday at midnight check for new releases"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and merge upstream repo
        uses: dabreadman/sync-upstream-repo@fc5fe9952946b1daaafd9abd7fcd7e260b81ddbe # v1.3.0
        with:
          upstream_repo: "https://github.com/nix-community/NixOS-WSL.git"
          token: ${{ secrets.WORKFLOW_TOKEN }}

  tags:
    runs-on: ubuntu-latest
    needs:
      - sync
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          fetch-depth: 0

      - name: Checkout Tags
        id: checkout-tags
        uses: chachako/checkout-tags@73862076cf5db6d3cf51c6160b939d9fcf2799c2 # v1.0.2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      # The branches are how checkout tags above checks for new tags
      - name: Push branches
        if: ${{ steps.checkout-tags.outputs.up-to-date != 'true' }}
        run: |
          while read branch; do
            git push origin refs/heads/$branch
          done <<< "${{ steps.checkout-tags.outputs.branches }}"

      - name: Kick off workflows to build tags
        if: ${{ steps.checkout-tags.outputs.up-to-date != 'true' }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            const tags = `${{ steps.checkout-tags.outputs.tags }}`.split('\n')
            for (let i = 0; i < tags.length; i++) {
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'run_tag_arm.yml',
                ref: 'main',
                inputs: {
                  tag: tags[i],
                  latest: i == 0 ? "true" : "false"
                }
              })
            }
